### ISSUE TITLE
hikari config is not working

### ISSUE THREAD

**Issue by blling** [ehsaniara/spring-boot-multi-data-source#1]
I think the following config is not working:
```
hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: ReadHikariPool
```
I test it by change some config item to wrong number, but not throw exception on test, eg.,:
```
  datasource-read:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:testds2;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    hikari:
      idle-timeout: **1000xcvsdf0**
      maximum-pool-size: **10xv**
      minimum-idle: **5xcv**
      pool-name: ReadHikariPool
```

**Comment by ehsaniara** [comment]
In Spring Boot 2.X, Hikari is the default DataSource implementation. so your hikari config should be under `spring` configuration as:
```
spring.datasource-read.hikari:
  connectionTimeout: 30000
  idleTimeout: 600000
  ...
```

**Comment by blling** [comment]
Yeah, i don`t change the config structure, i just change the value, the full config as follows:
```
spring:
  datasource-write:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:testds1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    hikari:
      idle-timeout: 100sdfs00
      maximum-pool-size: 1sdf0
      minimum-idle: 5df
      pool-name: WriteHikariPool

  datasource-read:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:testds2;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    hikari:
      idle-timeout: **1000xcvsdf0**
      maximum-pool-size: **10xv**
      minimum-idle: **5xcv**
      pool-name: ReadHikariPool
```
The debug screenshot:
![图片](https://user-images.githubusercontent.com/26540808/75638976-83c0e600-5c69-11ea-82a2-fbcdaafd1356.png)
the `poolName` and other hikari config is not set as expected.
